### ISSUE TITLE
Don't use <center> in index.html

### ISSUE THREAD

**Issue by Feliix42** [kiliankoe/kilian.sexy#1]
Also erstmal muss ich sagen, dass das wirklich eine sehr sexy Webseite ist! Aber in HTML 5 wird **<center>** leider nicht mehr unterstützt. Du solltest dringend über ein CSS-Script nachdenken. :D

**Comment by kiliankoe** [comment]
Pff, wer nutzt schon html5 :D

Aber ne, hast schon Recht^^ Dann muss der @hoodie aber auch gleich mit ran an seine Seite :P

**Comment by hoodie** [comment]
So this is not idiomatic html5 :question:

**Comment by kiliankoe** [comment]
![](http://i.giphy.com/Lhdwd9aueCeR2.gif)

**Comment by hoodie** [comment]
you should ![fun](http://i.giphy.com/MTclfCr4tVgis.gif)

**Comment by kiliankoe** [comment]
F is for friends who do stuff together! U is for you and me! N is for anywhere at any time at all down here in the deep blue sea!

Werd' ich niemals vergessen :D

**Comment by kiliankoe** [comment]
In f36794f5b16e82302355d52e71c33a6d7c38058a gefixt^^

**Comment by hoodie** [comment]
Safari kann kein transform?
![Oh no!](http://i.giphy.com/10XpbAw59H1mog.gif)

**Comment by kiliankoe** [comment]
Sollte alles gehen, dein Code war schuld! :D 

Abgesehen davon ist's wie ich vorhin gemeint hab' eh so dermaßen overkill, hier mit nem translate zu kommen. Und jetzt pack' deinen Bootstrap Kram wieder ein, bevor da noch was draus wird! :D

**Comment by hoodie** [comment]
tz tz tz
